name: EzGz Tests

on:
    pull_request:
        branches: [master]
    push:
        branches: [master, ezgz_yml_cleanup]
jobs:
  ezgz_test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30  # Set a custom timeout (e.g., 30 minutes)

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        standard: [17, 20] # This corresponds to C++17 and C++20

    env:
      BUILD_DIR: build
      EXECUTABLE: ''
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up CMake
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          echo "EXECUTABLE=build/bin/Release/ezgz_test.exe" >> $GITHUB_ENV
        else
          echo "EXECUTABLE=build/bin/ezgz_test" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Create build directory
      run: mkdir -p ${{ env.BUILD_DIR }}

    - name: Configure with CMake
      run: |
        cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_CXX_STANDARD=${{ matrix.standard }}

    - name: Build with CMake
      run: |
        cmake --build ${{ env.BUILD_DIR }} --config Release

    - name: Run Tests
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          ${{ env.EXECUTABLE }}
        else
          chmod +x ${{ env.EXECUTABLE }}
          ./${{ env.EXECUTABLE }}
        fi
      shell: bash
